### ISSUE TITLE
core dump on download

### ISSUE THREAD

**Issue by jungle-boogie** [cznic/sqlite3shell#2]
Hello,

Looking forward to trying this out on my openBSD -current 64bit machine, but I get a core dump. Unfortunately, there's no symbols.

```
$ go get github.com/cznic/sqlite3shell/issues
Abort trap (core dumped)
sean@puffer:~$ gdb /usr/local/bin/go
go             gobject-query  gofmt          gost-hash
$ gdb /usr/local/bin/go go.core
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-unknown-openbsd6.3"...Dwarf Error: wrong version in compilation unit header (is 4, should be 2) [in module /usr/local/bin/go]

Core was generated by `go'.
Program terminated with signal 6, Aborted.
Reading symbols from /usr/lib/libpthread.so.25.1...done.
Loaded symbols for /usr/lib/libpthread.so.25.1
Symbols already loaded for /usr/lib/libpthread.so.25.1
Reading symbols from /usr/lib/libc.so.92.3...done.
Loaded symbols for /usr/lib/libc.so.92.3
Reading symbols from /usr/libexec/ld.so...done.
Loaded symbols for /usr/libexec/ld.so
#0  0x00000000004595e1 in ?? ()
(gdb) bt
#0  0x00000000004595e1 in ?? ()
#1  0x0000000000000000 in ?? ()
```

**Comment by cznic** [comment]
As far as I know, modulo some possible security issue, `go get` does not execute any code in the downloaded repository, so this looks like a problem rooted somewhere else than in the code of `sqlite3shell`.

Please note, that the import path in the OP is wrong, it has an extra `/issues` part. Maybe that makes `go get` crash? If that's the case it would be probably worth reporting at the Go issue tracker.

Nonetheless, thanks for you interest in trying the code. ATM it will *not* build on BSD anyway, but I consider porting it to be rather easy. If you would like to give it a try, I'll prepare stubs necessary for porting `cznic/virtual` and `cznic/ccir` to BSD. That are the prerequisities that will enable `cznic/slite2go` to produce `sqlite3shell` runnable on BSD. WDYT?

**Comment by jungle-boogie** [comment]
> Please note, that the import path in the OP is wrong,

yeah, that's my mistake.  Still crashes with the correct URL, though:

```
$ go get github.com/cznic/sqlite3shell
Abort trap (core dumped)
```

**Comment by jungle-boogie** [comment]
hmm, okay, I don't think this issue is specific to your project.

```
$ go get -u github.com/justwatchcom/gopass
Abort trap (core dumped)
```

This project had no issues building a week or two ago.
